# Transform GPS nav data to ros2 map based data
navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0

    # IMU is calibrated
    magnetic_declination_radians: 0.0

    # IMU yaw=0 north, needs yaw=0 east pi/2 offset
    yaw_offset: 0.0 #1.5707963

    zero_altitude: true
    broadcast_utm_transform: true
    publish_filtered_gps: true
    use_odometry_yaw: false # use IMU compass #true
    wait_for_datum: true # ? does not seem to wait so I had to set datum here
    datum: [32.770227,  -96.8377377, 0.0] # House, [lat, lon, alt]